from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Sequence, Set, Tuple

from uptowes.lexicon_runtime import norm_text


def _normalize_token(token: str) -> str:
    return norm_text(token)


def _hash_file(path: str | Path) -> str:
    p = Path(path)
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _token_set(items: Iterable[Any]) -> Set[str]:
    out: Set[str] = set()
    for item in items:
        tok = _normalize_token(str(item or ""))
        if tok:
            out.add(tok)
    return out


def _format_py_set(values: Sequence[str]) -> str:
    if not values:
        return "set()"
    return "{" + ", ".join(repr(v) for v in values) + "}"


def _emit_lexicon_py(
    out_py_path: Path,
    groups: Mapping[str, Mapping[str, Any]],
    aliases: Mapping[str, str],
    short_allow: Sequence[str],
    *,
    spec_sha256: str,
    banned_sha256: str,
    source_spec_path: Path,
    source_banned_path: Path,
    lexicon_id: str,
    lexicon_version: str,
) -> None:
    lines: List[str] = []
    lines.append("# Auto-generated by src/uptowes/lexicon/build_from_spec.py")
    lines.append(f"# source_spec_path: {source_spec_path}")
    lines.append(f"# source_banned_path: {source_banned_path}")
    lines.append(f"# source_spec_sha256: {spec_sha256}")
    lines.append(f"# source_banned_sha256: {banned_sha256}")
    lines.append("# NOTE: TEMPORARY POLICY - tokens in ambiguous_cross_area are banned")
    lines.append("# until co-occurrence support exists in expand_query/retrieval.")
    lines.append("")
    lines.append(f"LEXICON_ID = {lexicon_id!r}")
    lines.append(f"LEXICON_VERSION = {lexicon_version!r}")
    lines.append("")
    lines.append("LEX_GROUPS = {")
    for gid in sorted(groups.keys()):
        g = groups[gid]
        lines.append(f"    {gid!r}: {{")
        lines.append(f"        'canonical': {str(g.get('canonical') or '')!r},")
        lines.append(f"        'variants': {list(g.get('variants') or [])!r},")
        for k in sorted(g.keys()):
            if k in {"canonical", "variants"}:
                continue
            lines.append(f"        {k!r}: {g[k]!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("LEX_ALIASES = {")
    for alias in sorted(aliases.keys()):
        lines.append(f"    {alias!r}: {aliases[alias]!r},")
    lines.append("}")
    lines.append("")
    lines.append(f"SHORT_TOKEN_ALLOWLIST = {_format_py_set(sorted(short_allow))}")
    lines.append("")

    out_py_path.parent.mkdir(parents=True, exist_ok=True)
    out_py_path.write_text("\n".join(lines), encoding="utf-8")


def _make_report_template(
    spec_path: Path,
    banned_path: Path,
    spec_sha256: str,
    banned_sha256: str,
) -> Dict[str, Any]:
    return {
        "generated_at": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "inputs": {
            "spec_path": str(spec_path),
            "banned_path": str(banned_path),
            "spec_sha256": spec_sha256,
            "banned_sha256": banned_sha256,
        },
        "normalization": {"changed_tokens": [], "deduped_variants_count": 0},
        "banlist": {"removed_tokens": [], "removed_tokens_count": 0},
        "ambiguous_temp_ban": {"removed_tokens": [], "removed_tokens_count": 0},
        "canonical_promoted": [],
        "groups": {
            "total_in_spec": 0,
            "total_emitted": 0,
            "groups_failed_empty": [],
        },
        "aliases": {
            "total_emitted": 0,
            "collisions_detected": [],
        },
        "short_token_allowlist": {"count": 0, "tokens": []},
    }


def _append_changed(report: MutableMapping[str, Any], *, token_from: str, token_to: str, context: str) -> None:
    report["normalization"]["changed_tokens"].append(  # type: ignore[index]
        {"from": token_from, "to": token_to, "context": context}
    )


def _append_removed(report: MutableMapping[str, Any], *, token: str, reason: str, context: str) -> None:
    target = "ambiguous_temp_ban" if reason == "ambiguous_cross_area" else "banlist"
    report[target]["removed_tokens"].append({"token": token, "reason": reason, "context": context})  # type: ignore[index]


def _sanitize_token(
    raw_token: str,
    *,
    context: str,
    stopwords: Set[str],
    html_artifacts: Set[str],
    units_numbers: Set[str],
    ambiguous: Set[str],
    report: MutableMapping[str, Any],
) -> Tuple[str, str | None]:
    normalized = _normalize_token(str(raw_token or ""))
    if normalized != str(raw_token or ""):
        _append_changed(report, token_from=str(raw_token or ""), token_to=normalized, context=context)
    if not normalized:
        return "", "empty"
    if normalized in stopwords:
        _append_removed(report, token=normalized, reason="stopwords_pt", context=context)
        return "", "stopwords_pt"
    if normalized in html_artifacts:
        _append_removed(report, token=normalized, reason="html_artifacts", context=context)
        return "", "html_artifacts"
    if normalized in units_numbers:
        _append_removed(report, token=normalized, reason="units_numbers", context=context)
        return "", "units_numbers"
    if normalized in ambiguous:
        _append_removed(report, token=normalized, reason="ambiguous_cross_area", context=context)
        return "", "ambiguous_cross_area"
    return normalized, None


def build_lexicon_from_spec(
    spec_path: str | Path,
    banned_path: str | Path,
    out_py_path: str | Path,
    out_report_path: str | Path,
) -> None:
    spec_p = Path(spec_path)
    banned_p = Path(banned_path)
    out_py_p = Path(out_py_path)
    out_report_p = Path(out_report_path)

    spec_obj = _load_json(spec_p)
    banned_obj = _load_json(banned_p)
    spec_sha = _hash_file(spec_p)
    banned_sha = _hash_file(banned_p)

    report = _make_report_template(spec_p, banned_p, spec_sha, banned_sha)
    groups_raw = dict(spec_obj.get("LEX_GROUPS") or {})
    aliases_raw = dict(spec_obj.get("LEX_ALIASES") or {})
    report["groups"]["total_in_spec"] = len(groups_raw)  # type: ignore[index]

    banned_categories = dict(banned_obj.get("banned_categories") or {})
    stopwords = _token_set(((banned_categories.get("stopwords_pt") or {}).get("tokens") or []))
    html_artifacts = _token_set(((banned_categories.get("html_artifacts") or {}).get("tokens") or []))
    units_numbers = _token_set(((banned_categories.get("units_numbers") or {}).get("tokens") or []))
    ambiguous = _token_set(((banned_categories.get("ambiguous_cross_area") or {}).get("tokens") or []))

    sanitized_groups: Dict[str, Dict[str, Any]] = {}
    for gid in sorted(groups_raw.keys()):
        g = dict(groups_raw.get(gid) or {})
        canonical_original = str(g.get("canonical") or "")
        variants_original = [str(v or "") for v in (g.get("variants") or [])]
        removed_before = (
            len(report["banlist"]["removed_tokens"]) + len(report["ambiguous_temp_ban"]["removed_tokens"])  # type: ignore[index]
        )

        canonical_norm = _sanitize_token(
            canonical_original,
            context="canonical",
            stopwords=stopwords,
            html_artifacts=html_artifacts,
            units_numbers=units_numbers,
            ambiguous=ambiguous,
            report=report,
        )
        canonical_token, canonical_removed_reason = canonical_norm

        variants_norm: List[str] = []
        seen: Set[str] = set()
        for v in variants_original:
            tok, _ = _sanitize_token(
                v,
                context="group_variant",
                stopwords=stopwords,
                html_artifacts=html_artifacts,
                units_numbers=units_numbers,
                ambiguous=ambiguous,
                report=report,
            )
            if not tok:
                continue
            if tok in seen:
                report["normalization"]["deduped_variants_count"] += 1  # type: ignore[index]
                continue
            seen.add(tok)
            variants_norm.append(tok)
        variants_norm = sorted(variants_norm)

        removed_after = (
            len(report["banlist"]["removed_tokens"]) + len(report["ambiguous_temp_ban"]["removed_tokens"])  # type: ignore[index]
        )
        removed_count_for_group = removed_after - removed_before

        if not variants_norm:
            report["groups"]["groups_failed_empty"].append(  # type: ignore[index]
                {
                    "group_id": gid,
                    "canonical_original": canonical_original,
                    "variants_orig_count": len(variants_original),
                    "removed_tokens_count": removed_count_for_group,
                }
            )
            continue

        if not canonical_token:
            promoted = min(variants_norm)
            banned_union = stopwords | html_artifacts | units_numbers | ambiguous
            if promoted in banned_union:
                report["groups"]["groups_failed_empty"].append(  # type: ignore[index]
                    {
                        "group_id": gid,
                        "canonical_original": canonical_original,
                        "variants_orig_count": len(variants_original),
                        "removed_tokens_count": removed_count_for_group,
                    }
                )
                continue
            report["canonical_promoted"].append(  # type: ignore[index]
                {
                    "group_id": gid,
                    "from": _normalize_token(canonical_original),
                    "to": promoted,
                    "reason": canonical_removed_reason or "canonical_removed",
                }
            )
            canonical_token = promoted

        # Keep deterministic and unique variants.
        variants_norm = sorted(set(variants_norm))

        out_group: Dict[str, Any] = {"canonical": canonical_token, "variants": variants_norm}
        for k in sorted(g.keys()):
            if k in {"canonical", "variants"}:
                continue
            out_group[k] = g[k]
        sanitized_groups[gid] = out_group

    report["groups"]["total_emitted"] = len(sanitized_groups)  # type: ignore[index]

    sanitized_aliases: Dict[str, str] = {}
    alias_first_seen: Dict[str, str] = {}
    for alias_raw in sorted(aliases_raw.keys()):
        gid = str(aliases_raw[alias_raw] or "").strip()
        alias_norm, _ = _sanitize_token(
            str(alias_raw or ""),
            context="alias_key",
            stopwords=stopwords,
            html_artifacts=html_artifacts,
            units_numbers=units_numbers,
            ambiguous=ambiguous,
            report=report,
        )
        if not alias_norm:
            continue
        if gid not in sanitized_groups:
            continue
        prev = alias_first_seen.get(alias_norm)
        if prev is not None and prev != gid:
            report["aliases"]["collisions_detected"].append(  # type: ignore[index]
                {"alias": alias_norm, "group_a": prev, "group_b": gid}
            )
            continue
        alias_first_seen[alias_norm] = gid
        sanitized_aliases[alias_norm] = gid

    report["aliases"]["total_emitted"] = len(sanitized_aliases)  # type: ignore[index]

    short_allow = sorted({k for k in sanitized_aliases.keys() if 2 <= len(k) <= 3})
    banned_union = stopwords | html_artifacts | units_numbers | ambiguous
    short_allow = [t for t in short_allow if t not in banned_union and len(t) > 1]
    report["short_token_allowlist"]["count"] = len(short_allow)  # type: ignore[index]
    report["short_token_allowlist"]["tokens"] = short_allow  # type: ignore[index]

    report["banlist"]["removed_tokens_count"] = len(report["banlist"]["removed_tokens"])  # type: ignore[index]
    report["ambiguous_temp_ban"]["removed_tokens_count"] = len(report["ambiguous_temp_ban"]["removed_tokens"])  # type: ignore[index]
    report["canonical_promoted"] = sorted(report["canonical_promoted"], key=lambda x: x["group_id"])  # type: ignore[index]

    out_report_p.parent.mkdir(parents=True, exist_ok=True)
    out_report_p.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    group_failures = list(report["groups"]["groups_failed_empty"])  # type: ignore[index]
    if group_failures:
        first = group_failures[0]
        raise ValueError(
            "GROUP_EMPTY_AFTER_BAN "
            f"group_id=\"{first['group_id']}\" "
            f"canonical_original=\"{first['canonical_original']}\" "
            f"variants_orig_count={first['variants_orig_count']} "
            f"removed_tokens_count={first['removed_tokens_count']}"
        )

    collisions = list(report["aliases"]["collisions_detected"])  # type: ignore[index]
    if collisions:
        c = collisions[0]
        raise ValueError(
            f"ALIAS_COLLISION alias=\"{c['alias']}\" "
            f"group_a=\"{c['group_a']}\" group_b=\"{c['group_b']}\" "
            f"source_path=\"{spec_p}\""
        )

    lexicon_id = str((spec_obj.get("_meta") or {}).get("version") or "ptbr_core_v1")
    lexicon_version = str((spec_obj.get("_meta") or {}).get("generated_at") or "v1")
    _emit_lexicon_py(
        out_py_p,
        groups=sanitized_groups,
        aliases=sanitized_aliases,
        short_allow=short_allow,
        spec_sha256=spec_sha,
        banned_sha256=banned_sha,
        source_spec_path=spec_p,
        source_banned_path=banned_p,
        lexicon_id=lexicon_id,
        lexicon_version=lexicon_version,
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True, help="Path to spec JSON")
    ap.add_argument("--banned", required=True, help="Path to banned JSON")
    ap.add_argument("--out-py", required=True, help="Output lexicon .py")
    ap.add_argument("--out-report", required=True, help="Output build report .json")
    args = ap.parse_args()

    build_lexicon_from_spec(
        spec_path=args.spec,
        banned_path=args.banned,
        out_py_path=args.out_py,
        out_report_path=args.out_report,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
